spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/restaurante
    username: postgres
    password: mysecretpassword
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
      