spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/loja
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      database: loja
      host: 172.17.0.2

server:
  servlet:
    context-path: /api
  port: 8081